In [1]:
import pandas as pd
import numpy as np
import re
import os

In [2]:
data = pd.read_csv('Dataset.csv')

In [3]:
data


Date  Day  Age        BMI Sex  Ticket Size Slab  Window  Discount  \
0      4/1/2011  Fri   41  20.423548   F          140    L      23        72   
1      4/1/2011  Fri   20  22.244202   F          140    M      47        80   
2      4/1/2011  Fri   24  21.369013   M          160    M      10        83   
3      4/1/2011  Fri   27  21.182299   M          120    M      22        92   
4      4/1/2011  Fri   22  18.087382   M          140    S      25        52   
5      4/1/2011  Fri   37  20.767922   M          180    M      44        19   
6      4/1/2011  Fri   34  24.606113   M          160    S       2        77   
7      4/1/2011  Fri   22  21.997529   F          180    M      46        23   
8      4/1/2011  Fri   30  18.298808   F          140    M      44         5   
9      4/1/2011  Fri   42  18.007538   M          140    S       6        59   
10     4/1/2011  Fri   35  26.371429   M          180    M      26        25   
11     4/1/2011  Fri   21  23.446236   M          140    S       7        12   
12     4/1/2011  Fri   26  23.924272   M          180    L      22        93   
13     4/1/2011  Fri   37  21.426957   F          160    M      16        96   
14     4/1/2011  Fri   43  15.714864   M          120    L      25        26   
15     4/1/2011  Fri   43  22.263721   M          120    S      29        46   
16     4/1/2011  Fri   22  24.859297   F          140    M      30        68   
17     4/1/2011  Fri   37  21.768918   F          160    M      42        71   
18     4/1/2011  Fri   43  23.285875   F          180    S       4        60   
19     4/1/2011  Fri   25  21.705144   F          160    S      12        16   
20     4/1/2011  Fri   40  18.849469   M          160    S      33        52   
21     4/1/2011  Fri   30  17.549408   F          160    L      11        16   
22     4/1/2011  Fri   33  21.932930   M          140    L      14        37   
23     4/2/2011  Sat   27  23.238634   F          140    L       4        41   
24     4/2/2011  Sat   30  22.671724   M          140    S      18        48   
25     4/2/2011  Sat   36  21.314652   F          120    S      37        56   
26     4/2/2011  Sat   22  18.511968   F          180    M      42        59   
27     4/2/2011  Sat   31  17.285054   M          180    L      41        90   
28     4/2/2011  Sat   39  24.623204   M          160    S      30        97   
29     4/2/2011  Sat   35  20.220642   M          140    L      41        12   
...         ...  ...  ...        ...  ..          ...  ...     ...       ...   
2694  6/30/2011  Thu   30  20.880386   M          160    L      29         9   
2695  6/30/2011  Thu   30  28.492991   M          140    S      19        93   
2696  6/30/2011  Thu   32  20.389673   F          180    M      21         7   
2697  6/30/2011  Thu   23  22.047830   M          180    M       1        92   
2698  6/30/2011  Thu   42  19.557817   F          120    S      28        77   
2699  6/30/2011  Thu   23  23.475507   F          160    S       2        48   
2700  6/30/2011  Thu   44  22.041280   F          160    M      12        95   
2701  6/30/2011  Thu   37  17.900004   F          180    S      10        32   
2702  6/30/2011  Thu   22  20.055211   F          160    S       1        74   
2703  6/30/2011  Thu   26  24.177522   F          180    M      40        32   
2704  6/30/2011  Thu   26  18.696198   F          180    S      27        62   
2705  6/30/2011  Thu   23  16.365382   M          160    M      10        37   
2706  6/30/2011  Thu   41  23.800251   F          160    M       7        19   
2707  6/30/2011  Thu   36  20.082780   M          160    M      28        99   
2708  6/30/2011  Thu   34  23.349419   M          140    S      45        93   
2709  6/30/2011  Thu   44  21.949576   F          160    L      34        14   
2710  6/30/2011  Thu   22  20.344369   M          180    S      21        40   
2711  6/30/2011  Thu   22  16.624833   F          180    L      16        20   
2712  6/30/

In [4]:
state_preference = data['State Cuisine'].value_counts()
curry_preference = data['Curry'].value_counts()
spice_preference = data['Spice'].value_counts()

In [15]:
state_preference.index

Index([u'Punjab', u'Maharashtra', u'U.P.', u'South India', u'J&K', u'Haryana'], dtype='object')

In [5]:
data = data.sort('CustomerID',ascending=1)

C:\Users\ravindra\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':


In [6]:
data

Date  Day  Age        BMI Sex  Ticket Size Slab  Window  Discount  \
2347  6/20/2011  Mon   29  20.189371   M          120    L      43        31   
1609  5/28/2011  Sat   22  19.594627   M          160    L      15        56   
2596  6/27/2011  Mon   26  25.198189   M          140    M      44        58   
1654  5/30/2011  Mon   44  22.767058   F          140    L      33        14   
2130  6/14/2011  Tue   29  20.054441   M          120    L      26        32   
1582  5/27/2011  Fri   23  20.295224   F          120    M      47        35   
2163  6/15/2011  Wed   41  22.732704   M          140    L       1        32   
771    5/2/2011  Mon   28  25.981739   M          120    L      33        49   
1060  5/11/2011  Wed   42  18.695129   M          140    L      18        70   
2309  6/19/2011  Sun   34  21.640823   M          140    L      10        15   
202   4/10/2011  Sun   29  21.482646   M          120    L      41        75   
253   4/12/2011  Tue   43  22.037956   F          160    S      46        71   
1523  5/25/2011  Wed   20  21.907987   F          180    M      48        90   
704   4/29/2011  Fri   20  21.759601   M          160    S      29        88   
2117  6/14/2011  Tue   40  19.781529   F          140    L       2        93   
1914   6/7/2011  Tue   42  21.726071   F          120    S      30        26   
2479  6/24/2011  Fri   39  23.691816   F          120    M      17        87   
525   4/23/2011  Sat   35  17.758931   F          160    S       3        40   
2203  6/16/2011  Thu   27  20.100255   M          160    S       3        87   
612   4/26/2011  Tue   41  17.503515   F          140    S      18        10   
2196  6/16/2011  Thu   20  17.609558   M          160    M      23         1   
664   4/28/2011  Thu   41  19.637889   F          160    M      48        73   
992    5/8/2011  Sun   27  22.433863   M          180    S      46        13   
1090  5/11/2011  Wed   21  22.968214   F          180    M      21        72   
271   4/13/2011  Wed   43  19.796577   F          160    L      39        42   
2310  6/19/2011  Sun   41  17.134884   M          140    M      12        88   
2266  6/18/2011  Sat   29  19.482594   M          120    S      34        53   
2294  6/19/2011  Sun   28  23.173095   F          160    L      21        89   
229   4/11/2011  Mon   24  20.854363   M          180    M      14        72   
1010   5/9/2011  Mon   34  20.625204   M          180    S      48        58   
...         ...  ...  ...        ...  ..          ...  ...     ...       ...   
2637  6/28/2011  Tue   41  21.780235   F          120    L       6        62   
996    5/8/2011  Sun   37  24.451988   M          140    S      18        51   
2040  6/11/2011  Sat   26  27.331676   M          180    M      35       100   
1343  5/19/2011  Thu   36  26.043371   F          180    M      28        59   
214   4/10/2011  Sun   30  23.376461   F          180    L      10        86   
2492  6/24/2011  Fri   20  21.892433   M          160    M      44        69   
1773   6/3/2011  Fri   25  21.950007   F          160    S      15        78   
640   4/27/2011  Wed   41  21.346701   M          120    L      15        15   
1607  5/28/2011  Sat   34  19.488792   F          180    S      20        14   
2271  6/18/2011  Sat   32  17.099591   M          140    M       7        94   
1419  5/22/2011  Sun   24  22.488426   M          140    L       6         0   
1614  5/29/2011  Sun   23  17.270171   M          180    M      29        69   
2238  6/17/2011  Fri   27  23.185291   F          140    M       3        97   
2457  6/23/2011  Thu   30  24.024831   M          180    M      11        13   
473   4/21/2011  Thu   28  23.426958   F          120    M       7        73   
237   4/11/2011  Mon   29  23.001332   F          160    L       3        77   
736    5/1/2011  Sun   24  22.260266   M          140    L      26        35   
2060  6/12/2011  Sun   25  19.860886   M          120    M       6        50   
934    5/7/

In [7]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import LabelEncoder



In [8]:
le = LabelEncoder()
data = data[data.columns[:]].apply(le.fit_transform)
kmeans = KMeans(n_clusters = 10).fit(data)

In [9]:
data['labels'] = kmeans.labels_

In [10]:
data = data.sort('labels',ascending=1)
data

C:\Users\ravindra\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':


Date  Day  Age   BMI  Sex  Ticket Size  Slab  Window  Discount  Revenue  \
1682    54    5    6    49    0            0     1      38        12      242   
1639    53    1   22  1691    1            0     1       8        45      159   
710     21    0   20   360    1            2     0       2         2      324   
1279    39    6   13   642    1            0     2      46        25      209   
776     41    1   16   979    0            3     0       5        50      209   
1223    37    1    0   438    0            0     0      21        70       91   
1815    85    2   19   855    0            0     2      25        27      204   
1080    32    6   13  1020    1            2     1      41        58      161   
1475    46    5    5   349    0            2     0       0         4      320   
1254    38    5   24   677    1            0     1      37        78       66   
1504    47    6    6   883    0            1     0      33        63      128   
2404    75    6   23   887    0            1     1       8        33      217   
1902    88    5    2   922    0            0     2      17        55      132   
1072    32    6   19    94    0            1     1       1        29      230   
1662    53    1   12   986    0            3     0      21        96       16   
2215    68    4   21   468    1            2     2      22        46      202   
1276    38    5    9  1599    0            0     2      11        16      232   
1924    88    5   21  1326    0            2     2      41        79       84   
857     55    6   21  1094    0            1     1      31        92       27   
1971    90    4    9    88    0            3     1      43        50      209   
2645    81    5    4   747    1            2     0       7        84       65   
1097    33    4   20   551    0            3     2      16        32      276   
968     59    3   19   166    0            0     0      44         2      266   
1301    39    6    5   434    1            2     0      41        34      242   
559     16    3   23   158    1            0     1      23        48      150   
1855    86    3    2   629    0            2     0      27        33      246   
2253    69    0   24   341    1            0     1      21         4      261   
475     13    4   18   195    1            0     0      30        81       57   
1124    34    0   17  1212    0            1     1      46        92       27   
59      22    3   22   452    1            0     0      43        28      201   
...    ...  ...  ...   ...  ...          ...   ...     ...       ...      ...   
261      4    6   17   380    1            1     1      24        98        6   
2250    69    0   14   100    0            1     1       2         5      294   
1344    42    0    4   954    0            0     2      10         0      271   
2395    75    6   20   107    0            3     1      39        35      265   
1847    86    3   22   421    0            1     1      18        46      180   
287      5    4   14   286    0            3     2       4        59      175   
856     55    6    1   737    0            2     1      28         4      320   
417     10    5   24   482    1            2     0       5        17      293   
2710    84    4    2   897    1            3     2      20        40      248   
2605    80    1    2   277    1            1     1      33        52      161   
236      2    1   16   392    0            0     2      27        71       87   
1963    89    6    8     6    0            1     1      16        19      257   
488     14    0    8   670    0            2     2      19        10      310   
2352    73    1   13   413    1            3     2      17        91       40   
2571    79    3   18   648    1            2     1      39        84       65   
541     16    3   14   902    1            3     2      33        93       29   
1503    47    6    0   834    1            3     2      12        75      112   
2110    65    1   20   353    1      

In [34]:
df = data.set_index('CustomerID')

df = df.iloc[0:5, 16:20]

global df

df

ETA  Curry  Spice  Cancel
CustomerID                           
12            3     20     15       1
70           25     14      7       1
32           23     15      7       1
61           25     13     20       0
9             9      5     23       0

In [41]:
import operator

def Pearson_Correlation():
    data = np.array(df.values)
    rows = df.index.values
    
    (nrows,ncols) = data.shape
    
    Corr_val = {}
     
    for row1 in range(nrows):
        for row2 in range(nrows):
            if row1 != row2 :
                data_1 = [data[row1, :][n] for n in range(ncols) if data[row1,n]!=0 and data[row2,n] != 0]    
                data_2 = [data[row2, :][n] for n in range(ncols) if data[row1,n]!=0 and data[row2,n] != 0]    

                data_1 = np.array(data_1) - np.mean(data_1)
                data_2 = np.array(data_2) - np.mean(data_2)

                p_corr  = np.dot(data_1,data_2)*1.0 / np.sqrt(sum(np.power(data_1,2))*sum(np.power(data_2,2)))

                Corr_val[(rows[row1],rows[row2])] = p_corr  
            
            
            
    return Corr_val        
            
            
def Correlation_rank(user_id,n):
    
    p_corr = Pearson_Correlation()
    p_corr_row  = {}
    
    for i, j in p_corr.keys():
        if i == user_id:
            p_corr_row[(i,j)] = p_corr[(i,j)]

    sorted_p = sorted(p_corr_row,reverse = True, key=operator.itemgetter(1))[:n]         
    #print (p_corr_row)
    new_return = {} 
    for i , j in sorted_p:
        new_return[(i,j)] = p_corr_row[(i,j)]
        
    print (sorted_p)        
    return  new_return        



def prediction(user_id , n):
    
    ranked_p_rel = Correlation_rank(user_id,n)
    neigh_users = [b for(a,b) in  ranked_p_rel.keys()]
    
    #weights = ranked_p_rel
    
    pred = []
    
    
    
    for col in df.columns:
        vals = 0
        wghts = 0
        
        for neighb in neigh_users:
            val = df.loc[neighb,col]
            print val
            if val == 0:
                wght = 0
            
            
            else:
                wght = ranked_p_rel[(user_id,neighb)]
                
            vals += wght*val
            wghts += wght
            
            if wghts == 0:
                pred.append(0)
                
            else:
                pred.append(vals*1.0 / wghts)
                
                
    return pred



def recom(user_id,n,m):
    cols = df.columns.values
    pred = prediction(user_id,n)
    
    pred_dict={}
    #print pred
    for i in range(len(cols)):
        pred_dict[cols[i]] = pred[i]
        
    
    sorted_p = sorted(pred_dict,reverse = True, key=operator.itemgetter(1))[:m] 
    
   
    #print (sorted_p)        
    #return  new_return  
     
    for item in sorted_p:
        print item, "  ",pred_dict[item]
        
        
        
 



recom(user_id = 9,n = 4, m = 2)


            
              
                
    
    
    
    
    
    
    
    

            
            
            
            
        
        
    
    





[(9, 70), (9, 61), (9, 32), (9, 12)]
25
23
25
3
13
15
14
20
20
7
7
15
0
1
1
1
Curry    21.6055614625
Spice    23.6353833793


In [45]:
np.sum(df,axis = 0)

ETA       85
Curry     67
Spice     72
Cancel     3
dtype: int64

In [47]:
df.T.to_dict()[]

{9: {'Cancel': 0, 'Curry': 5, 'ETA': 9, 'Spice': 23},
 12: {'Cancel': 1, 'Curry': 20, 'ETA': 3, 'Spice': 15},
 32: {'Cancel': 1, 'Curry': 15, 'ETA': 23, 'Spice': 7},
 61: {'Cancel': 0, 'Curry': 13, 'ETA': 25, 'Spice': 20},
 70: {'Cancel': 1, 'Curry': 14, 'ETA': 25, 'Spice': 7}}

In [52]:


df1 =  pd.DataFrame(np.random.randint(low=0, high=2, size=(6, 5)), columns=['a', 'b', 'c', 'd', 'e'])

df2 =  pd.DataFrame(np.random.randint(low=-1, high=2, size=(6, 3)), columns=['u1', 'u2', 'u3'])


In [53]:
df2

u1  u2  u3
0  -1   1   1
1   0  -1   0
2   1  -1   0
3   1  -1   0
4   0   0   1
5   0   1  -1

In [56]:
spice = np.array(df1)
user = np.array(df2)
global spice
global user

In [71]:
# we have user_table which will give rating to a particular dish
# content based recommeder system
# we have 2 tables with us

#one is food - spices table and another is food-user rating table
#we will use tf-idf approach




#matrix of spice will contain only of 1 and 0's so need to normalize it

#normalization along the row
def spice_norm():
    
    num_attr = np.sum(spice,axis=1)
    doc_vec = []
    for i in range(num_attr.shape[0]):
        doc_vec.append(np.sqrt(spice[i,:]*1.0/num_attr[i]))
            
    return np.array(doc_vec)      
    
    
    
def attr_norm():
    
    num_attr = np.sum(spice,axis=0)
    
    doc_vec = []
    for i in range(num_attr.shape[0]):
        doc_vec.append(spice[:,i]*1.0 / num_attr[i])

    return np.array(doc_vec)

def user_v(spice_mat):
    user_vec = []
    
    for i in range(user.shape[1]):
        user_vec.append([np.dot(user[:,i],spice_mat[:,j]) for j in range(spice_mat.shape[1])])
    
    return np.array(user_vec)
    
def weight_predict(spice_mat):
        
    user_vec = user_v(spice_mat)
    
    preds = []
    
    for i in range(spice_mat.shape[0]):
        preds.append([np.dot(spice_mat[i,:],user_vec[j,:]) for j in range(user_vec.shape[0])])

    return np.array(preds)
    
    
def idf_weight_pred():
    spice_mat = spice_norm()
    attr_wght = attr_norm()
    print attr_wght
    weighted_spice = []
    
    for i in range(spice_mat.shape[0]):
        weighted_spice.append([np.dot(spice_mat[i,:],attr_wght[:,j]) for j in range(attr_wght.shape[0])])
        
    preds  = weight_predict(spice_mat = np.array(weighted_spice))     

    return np.array(preds)
    


preds = idf_weight_pred()

print preds












[[ 0.25  0.    0.    0.25  0.25  0.25]
 [ 0.    0.2   0.2   0.2   0.2   0.2 ]
 [ 0.25  0.25  0.25  0.25  0.    0.  ]
 [ 0.25  0.25  0.25  0.    0.    0.25]
 [ 0.    0.    0.    0.5   0.5   0.  ]]
[[ 0.47158908 -0.53408908  0.4375    ]
 [ 0.5056003  -0.6056003   0.4       ]
 [ 0.5056003  -0.6056003   0.4       ]
 [ 0.73421956 -0.73061112  0.68921188]
 [ 0.65183155 -0.60599821  0.62916667]
 [ 0.47170874 -0.50920874  0.42083333]]
